### ISSUE TITLE
#Add Chat Completion api 

### ISSUE THREAD

**Issue by huzaifansari54** [shamblett/huggingface_client#15]
**Add Chat Completion API**

 Here is docs  [chat completion ]( https://huggingface.co/docs/api-inference/tasks/chat-completion)

`from huggingface_hub import InferenceClient

client = InferenceClient(
    "google/gemma-2-2b-it",
    token="hf_***",
)

for message in client.chat_completion(
	messages=[{"role": "user", "content": "What is the capital of France?"}],
	max_tokens=500,
	stream=True,
):
    print(message.choices[0].delta.content, end="")
 `

**Comment by shamblett** [comment]
Done. Package re released at version 1.5.0
