### ISSUE TITLE
Failed host lookup: 'api-inference.huggingface.co'

### ISSUE THREAD

**Issue by magrcruz** [shamblett/huggingface_client#4]
I was trying the Text Classification task example but when I execute it it throws an exception
Failed host lookup: 'api-inference.huggingface.co'
OSError (OS Error: No address associated with hostname, errno = 7)
"No address associated with hostname"

**Comment by shamblett** [comment]
Seems to work OK here -
```
*** Text Classification Task ***

ApiResponseNLPTextClassification - [Label=POSITIVE, Score=0.9998738765716553]
ApiResponseNLPTextClassification - [Label=NEGATIVE, Score=0.00012611268903128803]
```

Your endpoint should have '/models' on the end, see the constant inferenceBasePath in hugging_face_client.dart, this is what the examples use 'HuggingFaceClient.inferenceBasePath'
